version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: springboot_app
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "chmod +x mvnw && ./mvnw package && java -jar target/demo-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
